import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CartProvider } from '@/context/CartContext'
import { ProductsProvider } from '@/context/ProductsContext'
import { Header } from '@/components/Header'
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Michael's Amazing Web Store",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsProvider>
          <CartProvider>
            <main className={styles.main}>
              <Header />
              {children}
            </main>
          </CartProvider>
        </ProductsProvider>
      </body>
    </html>
  )
}
